# 2020 Election Results Dataset

Identifying red, blue, and moderate states for future analysis on COVID search trends
     
     
MIT Election Data and Science Lab, 2017, "U.S. President 1976â€“2020", https://doi.org/10.7910/DVN/42MVDX, Harvard Dataverse, V8, UNF:6:F0opd1IRbeYI9QyVfzglUw== [fileUNF]

In [1]:
import pandas as pd

In [1]:
df = pd.read_csv("/Users/jackfeen/Downloads/1976-2020-president.csv")

NameError: name 'pd' is not defined

In [2]:
pd.set_option('display.max_columns', None)
df.head(2)

NameError: name 'pd' is not defined

We only care about the 2020 election results

In [4]:
df = df[df['year']==2020]
df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
3740,2020,ALABAMA,AL,1,63,41,US PRESIDENT,"BIDEN, JOSEPH R. JR",DEMOCRAT,False,849624,2323282,20210113,NaN,DEMOCRAT
3741,2020,ALABAMA,AL,1,63,41,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,1441170,2323282,20210113,NaN,REPUBLICAN
3742,2020,ALABAMA,AL,1,63,41,US PRESIDENT,"JORGENSEN, JO",LIBERTARIAN,False,25176,2323282,20210113,NaN,LIBERTARIAN
3743,2020,ALABAMA,AL,1,63,41,US PRESIDENT,NaN,NaN,True,7312,2323282,20210113,NaN,OTHER
3744,2020,ALASKA,AK,2,94,81,US PRESIDENT,"BIDEN, JOSEPH R. JR",DEMOCRAT,False,153778,359530,20210113,NaN,DEMOCRAT

I'll now initialize a dictionary that will be used later

In [7]:
state_affiliation = {
    "State": [],
    "State Code" : [],
    "Party Affiliation": []
}

Next, we compare the republican and democrat voting trends to classify states

In [8]:
heavily_red = []
heavily_blue = []
red = []
blue = []
moderate = []

grouped = df.groupby('state')

for state, group in grouped:
    dem_votes = group.loc[group['party_detailed'] == 'DEMOCRAT', 'candidatevotes'].values[0]
    rep_votes = group.loc[group['party_detailed'] == 'REPUBLICAN', 'candidatevotes'].values[0]
    
    dem_percentage = (dem_votes / group['candidatevotes'].sum()) * 100
    rep_percentage = (rep_votes / group['candidatevotes'].sum()) * 100

    if rep_percentage > dem_percentage + 22:
        affiliation = 'Heavily Red'
    elif dem_percentage > rep_percentage + 22:
        affiliation = 'Heavily Blue'
    elif rep_percentage > dem_percentage + 5:
        affiliation = 'Red'
    elif dem_percentage > rep_percentage + 5:
        affiliation = 'Blue'
    else:
        affiliation = 'Moderate'
        
    state_po = group['state_po'].values[0]  
    
    state_affiliation["State"].append(state)
    state_affiliation["State Code"].append(state_po)
    state_affiliation["Party Affiliation"].append(affiliation)

I'll finally put this data into a csv that I can use later to compare COVID-19 search trends with political affiliation

In [9]:
final_df = pd.DataFrame(state_affiliation)
final_df

                   State State Code Party Affiliation
0                ALABAMA         AL       Heavily Red
1                 ALASKA         AK               Red
2                ARIZONA         AZ          Moderate
3               ARKANSAS         AR       Heavily Red
4             CALIFORNIA         CA      Heavily Blue
5               COLORADO         CO              Blue
6            CONNECTICUT         CT              Blue
7               DELAWARE         DE              Blue
8   DISTRICT OF COLUMBIA         DC      Heavily Blue
9                FLORIDA         FL          Moderate
10               GEORGIA         GA          Moderate
11                HAWAII         HI      Heavily Blue
12                 IDAHO         ID       Heavily Red
13              ILLINOIS         IL              Blue
14               INDIANA         IN               Red
15                  IOWA         IA               Red
16                KANSAS         KS               Red
17              KENTUCKY         KY       Heavily Red
18             LOUISIANA         LA               Red
19                 MAINE         ME              Blue
20              MARYLAND         MD      Heavily Blue
21         MASSACHUSETTS         MA      Heavily Blue
22              MICHIGAN         MI          Moderate
23             MINNESOTA         MN              Blue
24           MISSISSIPPI         MS               Red
25              MISSOURI         MO               Red
26               MONTANA         MT               Red
27              NEBRASKA         NE               Red
28                NEVADA         NV          Moderate
29         NEW HAMPSHIRE         NH              Blue
30            NEW JERSEY         NJ              Blue
31            NEW MEXICO         NM              Blue
32              NEW YORK         NY      Heavily Blue
33        NORTH CAROLINA         NC          Moderate
34          NORTH DAKOTA         ND       Heavily Red
35                  OHIO         OH               Red
36              OKLAHOMA         OK       Heavily Red
37                OREGON         OR              Blue
38          PENNSYLVANIA         PA          Moderate
39          RHODE ISLAND         RI              Blue
40        SOUTH CAROLINA         SC               Red
41          SOUTH DAKOTA         SD       Heavily Red
42             TENNESSEE         TN       Heavily Red
43                 TEXAS         TX               Red
44                  UTAH         UT               Red
45               VERMONT         VT      Heavily Blue
46              VIRGINIA         VA              Blue
47            WASHINGTON         WA              Blue
48         WEST VIRGINIA         WV       Heavily Red
49             WISCONSIN         WI          Moderate
50               WYOMING         WY       Heavily Red

In [10]:
final_df.to_csv('Political_trends_by_state.csv', index=False)
print('done')

done

This csv file is useful, but for my own anaysis its better to combine it with the search trend data I pulled earlier

In [11]:
search_df = pd.read_csv('/Users/jackfeen/search-trends.csv')

In [12]:
search_df.head()

,Unnamed: 0,date,location_key,major_depressive_disorder,depression,manic_disorder,panic_attack,compulsive_behavior,compulsive_hoarding,shyness,suicidal_ideation,mood_disorder,mood_swing,underweight,guilt,impulsivity,anxiety,alcoholism
0,12818,2020-01-01,US,2.94,4.41,0.50,1.36,0.58,0.14,0.32,0.40,0.85,0.21,0.59,0.33,0.29,6.89,5.78
1,12819,2020-01-02,US,3.67,4.47,0.55,1.44,0.62,0.16,0.32,0.40,0.97,0.21,0.69,0.32,0.35,7.47,4.80
2,12820,2020-01-03,US,3.62,4.17,0.54,1.39,0.59,0.15,0.30,0.39,0.94,0.20,0.66,0.30,0.32,7.09,4.51
3,12821,2020-01-04,US,3.05,4.15,0.52,1.34,0.59,0.15,0.31,0.37,0.86,0.21,0.58,0.54,0.30,6.79,4.54
4,12822,2020-01-05,US,3.06,4.37,0.52,1.42,0.60,0.15,0.33,0.39,0.88,0.22,0.59,0.37,0.31,7.20,4.31

Match the syntax of the two dataframes to join on location_key

In [13]:
final_df['State Code'] = 'US_' + final_df['State Code']

In [14]:
final_df

                   State State Code Party Affiliation
0                ALABAMA      US_AL       Heavily Red
1                 ALASKA      US_AK               Red
2                ARIZONA      US_AZ          Moderate
3               ARKANSAS      US_AR       Heavily Red
4             CALIFORNIA      US_CA      Heavily Blue
5               COLORADO      US_CO              Blue
6            CONNECTICUT      US_CT              Blue
7               DELAWARE      US_DE              Blue
8   DISTRICT OF COLUMBIA      US_DC      Heavily Blue
9                FLORIDA      US_FL          Moderate
10               GEORGIA      US_GA          Moderate
11                HAWAII      US_HI      Heavily Blue
12                 IDAHO      US_ID       Heavily Red
13              ILLINOIS      US_IL              Blue
14               INDIANA      US_IN               Red
15                  IOWA      US_IA               Red
16                KANSAS      US_KS               Red
17              KENTUCKY      US_KY       Heavily Red
18             LOUISIANA      US_LA               Red
19                 MAINE      US_ME              Blue
20              MARYLAND      US_MD      Heavily Blue
21         MASSACHUSETTS      US_MA      Heavily Blue
22              MICHIGAN      US_MI          Moderate
23             MINNESOTA      US_MN              Blue
24           MISSISSIPPI      US_MS               Red
25              MISSOURI      US_MO               Red
26               MONTANA      US_MT               Red
27              NEBRASKA      US_NE               Red
28                NEVADA      US_NV          Moderate
29         NEW HAMPSHIRE      US_NH              Blue
30            NEW JERSEY      US_NJ              Blue
31            NEW MEXICO      US_NM              Blue
32              NEW YORK      US_NY      Heavily Blue
33        NORTH CAROLINA      US_NC          Moderate
34          NORTH DAKOTA      US_ND       Heavily Red
35                  OHIO      US_OH               Red
36              OKLAHOMA      US_OK       Heavily Red
37                OREGON      US_OR              Blue
38          PENNSYLVANIA      US_PA          Moderate
39          RHODE ISLAND      US_RI              Blue
40        SOUTH CAROLINA      US_SC               Red
41          SOUTH DAKOTA      US_SD       Heavily Red
42             TENNESSEE      US_TN       Heavily Red
43                 TEXAS      US_TX               Red
44                  UTAH      US_UT               Red
45               VERMONT      US_VT      Heavily Blue
46              VIRGINIA      US_VA              Blue
47            WASHINGTON      US_WA              Blue
48         WEST VIRGINIA      US_WV       Heavily Red
49             WISCONSIN      US_WI          Moderate
50               WYOMING      US_WY       Heavily Red

In [15]:
merged_df = pd.merge(final_df, search_df, left_on='State Code', right_on='location_key', how='outer')

In [16]:
merged_df.head()

,State,State Code,Party Affiliation,Unnamed: 0,date,location_key,major_depressive_disorder,depression,manic_disorder,panic_attack,compulsive_behavior,compulsive_hoarding,shyness,suicidal_ideation,mood_disorder,mood_swing,underweight,guilt,impulsivity,anxiety,alcoholism
0,ALABAMA,US_AL,Heavily Red,23053,2020-01-01,US_AL,3.16,4.05,0.57,1.30,0.52,0.12,0.30,0.35,0.89,0.26,0.54,0.33,0.30,6.93,5.04
1,ALABAMA,US_AL,Heavily Red,23054,2020-01-02,US_AL,4.35,4.51,0.56,1.47,0.52,0.13,0.29,0.40,0.99,0.21,0.62,0.31,0.38,7.41,4.39
2,ALABAMA,US_AL,Heavily Red,23055,2020-01-03,US_AL,4.18,4.07,0.51,1.46,0.56,0.12,0.26,0.38,0.92,0.23,0.61,0.27,0.33,7.24,4.15
3,ALABAMA,US_AL,Heavily Red,23056,2020-01-04,US_AL,3.46,4.02,0.55,1.46,0.55,0.11,0.33,0.38,0.89,0.20,0.48,0.51,0.29,7.03,4.00
4,ALABAMA,US_AL,Heavily Red,23057,2020-01-05,US_AL,3.46,4.50,0.58,1.35,0.56,0.12,0.28,0.35,0.94,0.23,0.56,0.37,0.36,7.12,3.91

In [17]:
merged_df.drop(columns=['State Code'], inplace=True)

In [18]:
merged_df.head()

,State,Party Affiliation,Unnamed: 0,date,location_key,major_depressive_disorder,depression,manic_disorder,panic_attack,compulsive_behavior,compulsive_hoarding,shyness,suicidal_ideation,mood_disorder,mood_swing,underweight,guilt,impulsivity,anxiety,alcoholism
0,ALABAMA,Heavily Red,23053,2020-01-01,US_AL,3.16,4.05,0.57,1.30,0.52,0.12,0.30,0.35,0.89,0.26,0.54,0.33,0.30,6.93,5.04
1,ALABAMA,Heavily Red,23054,2020-01-02,US_AL,4.35,4.51,0.56,1.47,0.52,0.13,0.29,0.40,0.99,0.21,0.62,0.31,0.38,7.41,4.39
2,ALABAMA,Heavily Red,23055,2020-01-03,US_AL,4.18,4.07,0.51,1.46,0.56,0.12,0.26,0.38,0.92,0.23,0.61,0.27,0.33,7.24,4.15
3,ALABAMA,Heavily Red,23056,2020-01-04,US_AL,3.46,4.02,0.55,1.46,0.55,0.11,0.33,0.38,0.89,0.20,0.48,0.51,0.29,7.03,4.00
4,ALABAMA,Heavily Red,23057,2020-01-05,US_AL,3.46,4.50,0.58,1.35,0.56,0.12,0.28,0.35,0.94,0.23,0.56,0.37,0.36,7.12,3.91

In [19]:
merged_df.to_csv('search_trends_w_political_affilation.csv', index=True)
print('done')

done